### ISSUE TITLE
Plan to support running in browser?

### ISSUE THREAD

**Issue by madhurakhal** [mattduffy/exiftool#7]
Is there any plan to make this lib to run in web browser?

**Comment by mattduffy** [comment]
No, exiftool is a perl binary executable that needs to be installed on the host system.  There is currently no way to directly interact with a native perl executable from inside the browser.  There is a project that attempts to replicate the features of exiftool in pure JS though, called [exiftool.js](https://github.com/mattburns/exiftool.js).  It is far from feature complete, and only works with JPEG files, but if that fits your needs, then I suggest trying that.

**Comment by madhurakhal** [comment]
Thank you for your update. Keep your good work.
